---
  tasks:
    - name: update apt repo and cache
      apt:
        update_cache: yes
    - name: install openjdk 8
      package:
        name: openjdk-8-jdk
        state: present
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        mode: '0755'
    - name: Add tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_user }}"
        shell: "{{ default_shell }}"
        home: "{{ tomcat_directory }}"
        group: "{{ tomcat_user }}"
    - name: installing tomcat using wget
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz "
        dest:  "{{ tomcat_directory }}"
        mode: '0755'
    - name: unzip tomcat
      unarchive:
        src:  "{{ tomcat_directory }}/apache-tomcat-7.0.109.tar.gz"
        dest: "{{ tomcat_directory }}"
        remote_src: true
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: "{{ tomcat_directory }}"
        recurse: yes
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        mode: '1777'
    - name: copy tomcat service file
      ansible.builtin.file:
        path: /etc/systemd/system/tomcat.service
        state: touch
        mode: '1777'
    - name: copy tomcat service file
      ansible.builtin.template:
        src: 'tomcatservice.j2'
        dest: /etc/systemd/system/tomcat.service
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        mode: '1777'
      notify:  daemon reload and start tomcat service
  handlers: 
    - name: daemon reload and start tomcat service
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        name: tomcat
